projectsyn/component-rook-ceph

Makefile, README.md, class/defaults.yml, class/rook-ceph.yml, component/cephcluster.libsonnet, component/cephfs.libsonnet, component/main.jsonnet, component/openshift.libsonnet, component/rbd.libsonnet, component/storagepool.libsonnet, docs/modules/ROOT/pages/how-tos/configure-ceph.adoc, docs/modules/ROOT/pages/how-tos/openshift4.adoc, docs/modules/ROOT/pages/how-tos/quick-start.adoc, docs/modules/ROOT/pages/index.adoc, docs/modules/ROOT/pages/references/parameters.adoc, docs/modules/ROOT/pages/tutorials/quick-start.adoc, docs/modules/ROOT/partials/nav.adoc, postprocess/patch_operator_deployment.jsonnet
=> Initial implementation

class/defaults.yml
=> Bump Rook.io version to v1.6.7

component/main.jsonnet
We add the following set of labels:
| Label                         | Value |
| ----------------------------- | ----- |
| `app.kubernetes.io/name`      | Set to `.metadata.name` of the resource |
| `app.kubernetes.io/managed-by`| `commodore` |
| `app.kubernetes.io/component` | `rook-ceph` |
As suggested in #3 
=> Add standard labels to resources managed by the component

class/defaults.yml
=> Update default Ceph version to v16.2.5

class/defaults.yml, component/storagepool.libsonnet, docs/modules/ROOT/pages/references/parameters.adoc
=> Add support for configuring mountOptions in StorageClasses

class/defaults.yml, class/rook-ceph.yml, component/alertrules.libsonnet, component/cephcluster.libsonnet, component/csi_metrics.libsonnet, component/helpers.libsonnet, component/main.jsonnet, component/storagepool.libsonnet, docs/modules/ROOT/pages/references/parameters.adoc
=> Implement managed set of Prometheus alert rules for Ceph

class/defaults.yml, docs/modules/ROOT/pages/references/parameters.adoc, postprocess/patch_operator_deployment.jsonnet
=> Bump rook version to 1.7.4

class/defaults.yml, docs/modules/ROOT/pages/references/parameters.adoc
=> Add component parameter to enable portable OSDs

class/defaults.yml
=> Fix indentation error in the default cephfs config

class/defaults.yml
=> Bump Rook to v1.7.7

class/defaults.yml, docs/modules/ROOT/pages/references/parameters.adoc
=> Tune CephFS default metadata/data ratio

component/cephcluster.libsonnet, component/cephfs.libsonnet, component/helpers.libsonnet, docs/modules/ROOT/pages/references/parameters.adoc
=> Configure CephFS metadata server (MDS) node affinity

docs/modules/ROOT/pages/runbooks/CephMdsMissingReplicas.adoc
=> Update `CephMdsMissingReplicas` alert runbook

class/defaults.yml, docs/modules/ROOT/pages/references/parameters.adoc
=> Configure default resource requests and limits for the CephFS MDS

docs/modules/ROOT/pages/how-tos/scale-cluster.adoc, docs/modules/ROOT/pages/how-tos/setup-cluster.adoc, docs/modules/ROOT/partials/nav.adoc
The how-tos assume that the cluster is being setup on an infrastructure which provides a CSI driver which supports both `volumeMode: Block` and volume expansion.
=> Add how-tos for setting up and scaling a PVC-based cluster

class/defaults.yml, docs/modules/ROOT/pages/references/parameters.adoc
=> Change default memory requests and limits of MDS deployments to 8Gi

.sync.yml, tests/defaults.yml
=> Configure modulesync

class/defaults.yml, component/alertrules.libsonnet, docs/modules/ROOT/pages/references/parameters.adoc
=> Add support for patching alert rules through the hierarchy

class/defaults.yml, tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/cluster-rbac.yaml, tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrole.yaml, tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrolebinding.yaml, tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/deployment.yaml, tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/psp.yaml, tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/role.yaml, tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/rolebinding.yaml, tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/serviceaccount.yaml, tests/golden/defaults/rook-ceph/rook-ceph/10_cephcluster_toolbox.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/cluster-rbac.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrole.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrolebinding.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/deployment.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/psp.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/role.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/rolebinding.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/serviceaccount.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/10_cephcluster_toolbox.yaml
=> Update `rook-ceph` to v1.8.9

docs/modules/ROOT/pages/runbooks/CephClusterWarningState.adoc
=> Add details about handling crashes to runbook ClusterWarningState

class/defaults.yml, docs/modules/ROOT/pages/runbooks/CephPoolGrowthWarning.adoc, tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/cluster-rbac.yaml, tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrole.yaml, tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrolebinding.yaml, tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/deployment.yaml, tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/role.yaml, tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/rolebinding.yaml, tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/serviceaccount.yaml, tests/golden/defaults/rook-ceph/rook-ceph/10_cephcluster_toolbox.yaml, tests/golden/defaults/rook-ceph/rook-ceph/40_alertrules.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/cluster-rbac.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrole.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrolebinding.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/deployment.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/role.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/rolebinding.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/serviceaccount.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/10_cephcluster_toolbox.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/40_alertrules.yaml
The renovate PRs look a bit broken, cf. #71 and #74 (version mismatch between commit/title and PR body)
=> Update Rook Helm chart and container image to v1.9.11

class/defaults.yml, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/deployment.yaml, tests/golden/defaults/rook-ceph/rook-ceph/10_cephcluster_configoverride.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/deployment.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/10_cephcluster_configoverride.yaml
=> Adjust `mon_data_avail_warn` to match the Kubelet's imageGCHigh threshold

class/defaults.yml, component/main.jsonnet, tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/cluster-rbac.yaml, tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrole.yaml, tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrolebinding.yaml, tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/deployment.yaml, tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/role.yaml, tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/rolebinding.yaml, tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/serviceaccount.yaml, tests/golden/defaults/rook-ceph/rook-ceph/10_cephcluster_toolbox.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/cluster-rbac.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrole.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrolebinding.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/deployment.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/role.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/rolebinding.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/serviceaccount.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/10_cephcluster_toolbox.yaml
=> Update to Rook v1.10.13

class/defaults.yml, component/alertrules.libsonnet, tests/golden/defaults/rook-ceph/rook-ceph/40_alertrules.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/40_alertrules.yaml, tests/openshift4.yml
=> Disable low-value alerts by default

class/defaults.yml, tests/golden/defaults/rook-ceph/rook-ceph/40_alertrules.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/40_alertrules.yaml
=> Remove more low-value alerts

class/defaults.yml, tests/golden/defaults/rook-ceph/rook-ceph/40_alertrules.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/40_alertrules.yaml
=> Configure recording rules for centralized Ceph dashboard

docs/modules/ROOT/pages/runbooks/CephOSDFlapping.adoc, docs/modules/ROOT/partials/runbooks/check_cephcluster_status.adoc
=> Include resolving steps in check_cephcluster_status partial

component/cephcluster.libsonnet, tests/golden/cephfs/rook-ceph/rook-ceph/10_cephcluster_rbac.yaml, tests/golden/defaults/rook-ceph/rook-ceph/10_cephcluster_rbac.yaml, tests/golden/openshift4/rook-ceph/rook-ceph/10_cephcluster_rbac.yaml
=> Rook v1.14: Add new `rook-ceph-default` SA to copy helper

component/openshift.libsonnet, tests/golden/openshift4/rook-ceph/rook-ceph/02_openshift_sccs.yaml
=> Rook v1.14: Add cluster default SA to OpenShift SCC
