projectsyn/component-rook-ceph

- class/defaults.yml
- postprocess/patch_operator_deployment.jsonnet
Not necessary to do this in postprocessing, as the Helm chart provides values for it.
> Enable RBD/CephFS CSI drivers via Helm values

- class/defaults.yml
- docs/modules/ROOT/pages/how-tos/configure-ceph.adoc
- docs/modules/ROOT/pages/references/parameters.adoc
The alerts shipped with Rook alert on the assumption that the cluster becomes read-only (OSD status `full`) at 85% capacity. However, by default, ceph configures the cluster's `full-ratio` at 95% capacity.
This commit adjusts the default full ratios to match the alerts we put in place.
Please note that the ratios configured in `config_override.global` only apply during Ceph cluster creation. To adjust the ratios at runtime, use `ceph osd set-{nearfull,backfillfull,full}-ratio <ratio>` in the `rook-ceph-tools` container on the cluster
> Configure CephCluster full ratios to match alerts

- class/defaults.yml
- docs/modules/ROOT/pages/references/parameters.adoc
This is not required on all clouds and actually causes repeated OSD crashes on cloudscale.ch on CSI-provisioned volumeMode=Block PVCs.
> Remove `osd.bluefs_buffered_io=false` from the default config

- class/rook-ceph.yml
Kapitan has changed the helm chart naming and release_name is
now deprecated.
> Rename the helm chart release_name variable for Kapitan to name

- docs/modules/ROOT/pages/runbooks/CephOSDDiskUnavailable.adoc
> Update CephOSDDiskUnavailable runbook

- component/aggregated_rbac.libsonnet
- component/main.jsonnet
- tests/golden/defaults/rook-ceph/rook-ceph/01_aggregated_rbac.yaml
- tests/golden/openshift4/rook-ceph/rook-ceph/01_aggregated_rbac.yaml
Most Rook-Ceph custom resources are namespaced, so users still need to be able to access the namespace to interact with the resources
We explicitly only aggregate view permissions for the cluster-scoped `ObjectBucket` resources to ClusterRole `cluster-reader`, which is always present on OpenShift 4, and can be setup on other distributions if desired.
Closes #34
> Add ClusterRoles to grant access to Rook-Ceph custom resources via aggregated ClusterRoles

- class/defaults.yml
- tests/golden/defaults/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/configmap.yaml
- tests/golden/openshift4/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/configmap.yaml
We need to configure tolerations for the provisioner pods to allow them to be scheduled on the storage nodes. Currently the provisioner pods are always scheduled elsewhere, because they don't tolerate the storage node taint.
> Allow CSI provisioner pods to be scheduled on the storage nodes

- component/openshift.libsonnet
- tests/golden/openshift4/rook-ceph/rook-ceph/02_openshift_sccs.yaml
This is required for Rook 1.9+ because new DaemonSets which manage the CSI driver's network namespace have been added in Rook 1.9. These DaemonSets run with the default ServiceAccount (this is currently not configurable), so we need to grant the default SA access to the Ceph-CSI SCC to allow those DaemonSet pods to be created on OpenShift 4.
See also https://github.com/rook/rook/pull/9643 and related implementation PRs
> Allow the default SA in the operator namespace to use the Ceph-CSI SCC

- class/defaults.yml
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/defaults/rook-ceph/rook-ceph/10_cephcluster_cluster.yaml
- tests/golden/openshift4/rook-ceph/rook-ceph/10_cephcluster_cluster.yaml
This PR:
- Reduces OSD CPU requests and limits.
Even the cluster with the heaviest workload barely uses 0.8 cores.
[Query](https://prometheus-k8s-openshift-monitoring.apps.cloudscale-lpg-2.appuio.cloud/graph?g0.expr=max_over_time%20(node_namespace_pod_container%3Acontainer_cpu_usage_seconds_total%3Asum_irate%7Bnamespace%3D~%22syn-rook-ceph-cluster%22%2Ccontainer%3D%22osd%22%7D%20%5B3h%5D)&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=9d&g0.end_input=2022-09-08%2013%3A54%3A26&g0.moment_input=2022-09-08%2013%3A54%3A26)
- Reduces MGR CPU/Memory requests and limits.
The managers are a non critical workload used for monitoring / management plugins and practically unused in our case. 
[Query](https://prometheus-k8s-openshift-monitoring.apps.cloudscale-lpg-2.appuio.cloud/graph?g0.expr= …
> Tune default resource requests

- component/main.jsonnet
- tests/golden/defaults/rook-ceph/rook-ceph/03_rbac_fixes.yaml
- tests/golden/openshift4/rook-ceph/rook-ceph/03_rbac_fixes.yaml
The Rook Helm chart removed permissions to `get` resource `nodes` from the clusterrole `cephfs-external-provisioner-runner` in commit https://github.com/rook/rook/commit/19f77c617407e6c0e87e5ae9f56ded4ba9955b86.
However, without permission to `get` resource `nodes`, the CephFS `csi-provisioner` container fails to provision new volumes with errors like the following.
```
E0216 14:19:44.814493       1 controller.go:957] error syncing claim "48498303-d89b-4e2d-b629-d52b1d30ec18": failed to get target node: nodes "worker-3b6c" is forbidden: User "system:serviceaccount:syn-rook-ceph-operator:rook-csi-cephfs-provisioner-sa" cannot get resource "nodes" in API group "" at the cluster scope
```
This commit creates an extra clusterrole and clusterrolebinding which grant the CephFS csi-provisioner …
> Add missing RBAC rule for CephFS `csi-provisioner`

- class/defaults.yml
- component/alertrules.libsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/defaults/rook-ceph/rook-ceph/40_alertrules.yaml
- tests/golden/openshift4/rook-ceph/rook-ceph/40_alertrules.yaml
- tests/openshift4.yml
This makes use of the new openshift4-monitoring library function introduced in https://github.com/appuio/component-openshift4-monitoring/pull/162
changelog.
> Add component parameter for configuring additional Prometheus rules

- class/defaults.yml
- tests/golden/defaults/rook-ceph/rook-ceph/40_alertrules.yaml
- tests/golden/openshift4/rook-ceph/rook-ceph/40_alertrules.yaml
With `irate()` there's a chance that the recording rules are flatlined at 0 even when there's bursts of activity on clusters with low overall utilization, if the bursts fall between the evaluation points.
Follow-up to #128 
changelog.
> Use `rate()` in recording rules

- docs/modules/ROOT/pages/how-tos/upgrade-ceph-csi-v3.9.adoc
- docs/modules/ROOT/partials/nav.adoc
- tests/golden/cephfs/rook-ceph/rook-ceph/99_cleanup.yaml
Follow-up for #114 and #115
changelog.
> Add how-to for upgrading to Ceph-CSI v3.9.0

- component/main.jsonnet
- component/restart-holder-ds.libsonnet
- tests/golden/cephfs/rook-ceph/rook-ceph/50_restart_holder_ds.yaml
- tests/golden/defaults/rook-ceph/rook-ceph/50_restart_holder_ds.yaml
- tests/golden/openshift4/rook-ceph/rook-ceph/50_restart_holder_ds.yaml
We check the holder pod's `metadata.labels.pod-template-generation` against the DaemonSet's `metadata.generation` to identify outdated pods.
The script waits until the node is drained by waiting until no non-daemonset pods are running and then deletes all holder pods on the node if any were identified as outdated.
changelog.
> Add support for replacing outdated CSI holder pods

- component/restart-holder-ds.libsonnet
- tests/golden/cephfs/rook-ceph/rook-ceph/50_restart_holder_ds.yaml
- tests/golden/defaults/rook-ceph/rook-ceph/50_restart_holder_ds.yaml
- tests/golden/openshift4/rook-ceph/rook-ceph/50_restart_holder_ds.yaml
This suppresses error messages like the following on installations which only have cephfs or rbd enabled, but not both.
```
Error from server (NotFound): daemonsets.apps "csi-rbdplugin-holder-cluster" not found
```
We don't care about the resulting value of the generation variable when the daemonset is missing, since we'll check an empty pod list for outdated pods in that case.
Additionally, we ensure that the holder-update DaemonSet pods are restarted when we modify the script by adding the script's md5sum as an annotation in the pod template.
Follow-up for #154 
changelog.
> Ignore `kubectl` error output when extracting current holder pod generation

- class/defaults.yml
- tests/golden/cephfs/rook-ceph/rook-ceph/10_cephcluster_cluster.yaml
- tests/golden/defaults/rook-ceph/rook-ceph/10_cephcluster_cluster.yaml
- tests/golden/openshift4/rook-ceph/rook-ceph/10_cephcluster_cluster.yaml
> Set default value for monitor healthcheck

- class/defaults.yml
- docs/modules/ROOT/pages/references/parameters.adoc
Rook `v1.14` changed the way `cephcsi` images are overridden and we accidentally already released a new `cephcsi` version in `v8`. Note: This change is a no-op together with https://github.com/projectsyn/component-rook-ceph/pull/144.
changelog.
> Fix `cephcsi` image override

- .cruft.json
- .github/workflows/test.yaml
- Makefile.vars.mk
- component/rbd.libsonnet
- component/storagepool.libsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/rbd-extra-storageclass/rook-ceph/rook-ceph/00_namespaces.yaml
- tests/golden/rbd-extra-storageclass/rook-ceph/rook-ceph/01_aggregated_rbac.yaml
- tests/golden/rbd-extra-storageclass/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/cluster-rbac.yaml
- tests/golden/rbd-extra-storageclass/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrole.yaml
- tests/golden/rbd-extra-storageclass/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/clusterrolebinding.yaml
- tests/golden/rbd-extra-storageclass/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/configmap.yaml
- tests/golden/rbd-extra-storageclass/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/deployment.yaml
- tests/golden/rbd-extra-storageclass/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/resources.yaml
- tests/golden/rbd-extra-storageclass/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/role.yaml
- tests/golden/rbd-extra-storageclass/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/rolebinding.yaml
- tests/golden/rbd-extra-storageclass/rook-ceph/rook-ceph/01_rook_ceph_helmchart/rook-ceph/templates/serviceaccount.yaml
- tests/golden/rbd-extra-storageclass/rook-ceph/rook-ceph/02_openshift_sccs.yaml
- tests/golden/rbd-extra-storageclass/rook-ceph/rook-ceph/03_rbac_fixes.yaml
- tests/golden/rbd-extra-storageclass/rook-ceph/rook-ceph/10_cephcluster_cluster.yaml
- tests/golden/rbd-extra-storageclass/rook-ceph/rook-ceph/10_cephcluster_configoverride.yaml
- tests/golden/rbd-extra-storageclass/rook-ceph/rook-ceph/10_cephcluster_rbac.yaml
- tests/golden/rbd-extra-storageclass/rook-ceph/rook-ceph/10_cephcluster_toolbox.yaml
- tests/golden/rbd-extra-storageclass/rook-ceph/rook-ceph/20_storagepools.yaml
- tests/golden/rbd-extra-storageclass/rook-ceph/rook-ceph/30_snapshotclasses.yaml
- tests/golden/rbd-extra-storageclass/rook-ceph/rook-ceph/30_storageclasses.yaml
- tests/golden/rbd-extra-storageclass/rook-ceph/rook-ceph/40_alertrules.yaml
- tests/golden/rbd-extra-storageclass/rook-ceph/rook-ceph/40_csi_driver_metrics.yaml
- tests/golden/rbd-extra-storageclass/rook-ceph/rook-ceph/99_cleanup.yaml
- tests/rbd-extra-storageclass.yml
This PR introduces a new parameter which allows users to easily configure additional storage classes for RBD blockpools managed by the component.
changelog.
> Add support for configuring additional storage classes for RBD blockpools

- component/alertrules.libsonnet
- component/cephcluster.libsonnet
- component/csi_metrics.libsonnet
- component/helpers.libsonnet
- component/main.jsonnet
> Add support for OKE as an OpenShift flavor

- class/defaults.yml
- class/rook-ceph.yml
> Switch Helm chart definition to Project Syn best practices
